name: 'Install GTK2 on Windows'
description:
  'Installs GTK2 binary for Windows, specifically for the RGtk2 package in R.'
author: 'Tom Elliott'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  arch:
    description:
      'The architecture of the GTK2 binary to install, comma-separated.'
    required: true
    default: '64'
  gtk_dir:
    description: 'The directory to install GTK2 to.'
    required: true
    default: 'C:\\GTK'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
